### ISSUE TITLE
Expert / Dense layer inner size

### ISSUE THREAD

**Issue by ozppupbg** [evintunador/minGrok#1]
Hello,

first, thank you for the nice implementation! But I noticed a small difference to the actual model, which caught my eye when I myself looked at the original implementation.

The FFN inner size for the experts is computed in a very weird way, the actual factor is about 5.33:
https://github.com/xai-org/grok-1/blob/7050ed204b8206bb8645c7b7bbef7252f79561b0/model.py#L85-L89
```
def ffn_size(emb_size, widening_factor):
    _ffn_size = int(widening_factor * emb_size) * 2 // 3
    _ffn_size = _ffn_size + (8 - _ffn_size) % 8  # ensure it's a multiple of 8
    logger.debug(f"emd_size: {emb_size} adjusted ffn_size: {_ffn_size}")
    return _ffn_size
```

Regards,

Jan

**Comment by evintunador** [comment]
Thanks I'm looking at my to-implement list rn and although I had the multiple of 8 part as not worth including, you're right somehow I completely missed the 2/3. Hoping to fix this and the other issue a YouTube commenter found later this afternoon
