### ISSUE TITLE
Mystery value 0.08838834764831845 solved

### ISSUE THREAD

**Issue by ozppupbg** [evintunador/minGrok#2]
Hello,

I just looked at this constant:
https://github.com/evintunador/minGrok/blob/11eb5cf06cd2011964c917e4e3bd575aea40d401/model.py#L87
and the value is 1/sqrt(128):
https://www.wolframalpha.com/input?i=0.08838834764831845%3D%3D1%2Fsqrt%28128%29
So it is the standard scaling by square root of dimension size.

**Comment by evintunador** [comment]
yes thanks, big brain fart on my part. someone else pointed it out in the YouTube comments a few days ago and it has since been corrected in the colab notebook tutorial but I've not bothered to do so in the .py file because I don't want to re-train another. thanks!
